let flags = [[ "blue", "blue", "blue", "blue", "blue", "blue", "red", "red", "red", "red", "red", "red", "red", "red", "red", "blue", "white", "blue", "white", "blue", "blue", "white", "white", "white", "white", "white", "white", "white", "white", "white", "blue", "blue", "white", "blue", "white", "blue", "red", "red", "red", "red", "red", "red", "red", "red", "red", "blue", "blue", "blue", "blue", "blue", "blue", "white", "white", "white", "white", "white", "white", "white", "white", "white", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red" ],[ "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "red", "red", "red", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "red", "red", "red", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "red", "red", "red", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white" ],["white", "white", "white", "white", "white", "white", "white", "red", "white", "white", "white", "white", "white", "white", "white",
"white", "white", "white", "white", "white", "white", "white", "red", "white", "white", "white", "white", "white", "white", "white",
"white", "white", "white", "white", "white", "white", "white", "red", "white", "white", "white", "white", "white", "white", "white",
"white", "white", "white", "white", "white", "white", "white", "red", "white", "white", "white", "white", "white", "white", "white",
"red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red",
"white", "white", "white", "white", "white", "white", "white", "red", "white", "white", "white", "white", "white", "white", "white",
"white", "white", "white", "white", "white", "white", "white", "red", "white", "white", "white", "white", "white", "white", "white",
"white", "white", "white", "white", "white", "white", "white", "red", "white", "white", "white", "white", "white", "white", "white",
"white", "white", "white", "white", "white", "white", "white", "red", "white", "white", "white", "white", "white", "white", "white"]];
let names=['USA','Japan','England'];